name: Tag Push Preperation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 4.2.0)'
        required: true

permissions:
  contents: write
  actions: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "TAG=v${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Get latest WPILib version
        id: get_wpilib
        run: |
          WPILIB_URL="https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/wpilibj/wpilibj-java/"
          LATEST=$(curl -s $WPILIB_URL | grep -oP '(?<=href=")[0-9]+\.[0-9]+\.[0-9]+(?=/")' | sort -Vr | head -n 1)
          echo "wpilib_version=$LATEST" >> $GITHUB_OUTPUT

      - name: Get latest AdvantageKit version
        id: get_ak
        run: |
          AK_VERSION=$(curl -s https://api.github.com/repos/Mechanical-Advantage/AdvantageKit/releases/latest | jq -r .tag_name)
          AK_VERSION=${AK_VERSION#v}
          echo "ak_version=$AK_VERSION" >> $GITHUB_OUTPUT

      - name: Update version numbers in source files
        run: |
          # Update vendordep JSON
          sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/" vendordeps_publish/AtlantisLib.json

          # Update Gradle build file
          sed -i "s/version = \".*\"/version = \"${VERSION}\"/" build.gradle.kts
          sed -i "s/val wpilibVersion = \".*\"/val wpilibVersion = \"${{ steps.get_wpilib.outputs.wpilib_version }}\"/" build.gradle.kts
          sed -i "s/val advantageKitVersion = \".*\"/val advantageKitVersion = \"${{ steps.get_ak.outputs.ak_version }}\"/" build.gradle.kts
          
          # Change the version and release link in README file
          sed -i "s/## Version: .*/## Version: ${VERSION}/" README.md
          sed -i "s|https://github.com/.*/releases/tag/v[0-9.]\\+|https://github.com/${REPO}/releases/tag/v${VERSION}|" README.md

      - name: Commit updated version files
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreplt.github.com"
          git add build.gradle.kts vendordeps_publish/ README.md
          git commit -m "Update version to ${{ env.VERSION }}" || echo "Nothing to commit"
          git push